schema: "classroom50/repo-config/v1"
classroom: "developing-the-interactive-web"
assignment: "lec-3"
secret: "coos6z1d"
owner:
  username: "bingo32"
  id: 72145265
  accepted_at: "2026-09-15T13:18:56Z"
